---
- name: Stop and disable {{ lb_name }}.service
  systemd:
    name: "{{ lb_name }}.service"
    enabled: false
    state: stopped
  ignore_errors: true

- name: Remove OpenShift 4 Loadbalancer SystemD service
  file:
    path: "/etc/systemd/system/{{ lb_name }}.service"
    state: absent

- name: checking if podman containers is running
  shell: "podman container list -a --format {% raw %} 'table {{.Names}} {{.ID}}' {% endraw %}|awk '/openshift-4-loadbalancer/ {print $2}'"
  register: running_containers
  become: yes

- name: get uuid for {{ lb_name }} container
  shell: podman ps -a | awk '/{{ lb_name }}/ {print $1}'
  register: container_uuid
  ignore_errors: yes

- name: stop running containers
  shell: "podman stop {{ item }}"
  become: yes
  with_items: "{{ running_containers.stdout_lines }}"
  when: running_containers.stdout != ""

- name: delete {{ podman_webserver }} container
  shell: "podman rm {{ item }}"
  when: running_containers.stdout != ""
  with_items: "{{ running_containers.stdout_lines }}"
  become: yes

- name: ensure {{ podman_webserver }} container is removed
  shell: "podman rm -f {{ container_uuid.stdout }}"
  ignore_errors: yes
  become: yes
